# Dockerfile
FROM python:3.9-slim

# Set work directory
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app /app

# Install dependencies
RUN pip install kafka-python

# Run the consumer
CMD ["python", "./app/consumer.py"]
