FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Copy wait-for-it script
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Expose the Flask port
EXPOSE 5000

# Run the application with wait-for-it
CMD ["/wait-for-it.sh", "kafka-broker:9092", "--", "python", "./app/ingest.py"]
