FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Copy wait-for-it script
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Expose application port (if needed, not necessary for this script)
EXPOSE 5000

# Accept KAFKA_BROKER as a build argument
ARG KAFKA_BROKER

# Set KAFKA_BROKER as an environment variable
ENV KAFKA_BROKER=${KAFKA_BROKER}

# Run the application with wait-for-it (using shell form)
CMD /wait-for-it.sh ${KAFKA_BROKER} -- python ./app/ingest.py