CREATE TABLE IF NOT EXISTS stock_data (
    id SERIAL PRIMARY KEY,
    stock_symbol VARCHAR(10) NOT NULL,
    local_time TIMESTAMP NOT NULL,
    open DOUBLE PRECISION,
    high DOUBLE PRECISION,
    low DOUBLE PRECISION,
    close DOUBLE PRECISION,
    volume DOUBLE PRECISION,
    SMA_5 DOUBLE PRECISION,
    EMA_10 DOUBLE PRECISION,
    delta DOUBLE PRECISION,
    gain DOUBLE PRECISION,
    loss DOUBLE PRECISION,
    avg_gain_10 DOUBLE PRECISION,
    avg_loss_10 DOUBLE PRECISION,
    rs DOUBLE PRECISION,
    RSI_10 DOUBLE PRECISION
);
